# -*- coding: utf-8 -*-
"""streamlit_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dZ-z9C_YRDDFKEQnBDV8ArBZ4y2KBfy1
"""

!pip install streamlit

!pip install streamlit pyngrok --quiet

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import random
# 
# st.set_page_config(page_title="😂 Mood Swing Machine", page_icon="🎭")
# 
# st.title("🎭 Mood Swing Machine")
# st.write("Welcome to the most unpredictable app you'll ever use!")
# 
# mood = st.selectbox("What’s your current vibe?", ["😄 Happy", "😢 Sad", "😡 Angry", "😴 Sleepy", "🤪 Crazy", "🤖 Robot Mode"])
# 
# jokes = {
#     "😄 Happy": [
#         "You're so bright, even the sun wears shades around you 😎",
#         "Happiness is contagious—stay away, I’m not insured!"
#     ],
#     "😢 Sad": [
#         "Don't cry... even onions feel bad when you cry 😢",
#         "If life gives you lemons, squirt them back in its eye!"
#     ],
#     "😡 Angry": [
#         "Take a deep breath... now scream into a pillow. Feel better? No? Good. 😂",
#         "Smash something! (Preferably the like button 👍)"
#     ],
#     "😴 Sleepy": [
#         "Coffee won’t help. But dreaming about coffee might ☕💤",
#         "Nap hard, nap proud 💤💪"
#     ],
#     "🤪 Crazy": [
#         "You clicked this on purpose, didn't you? Seek help. 😂",
#         "Bananas called. They want their crazy back 🍌"
#     ],
#     "🤖 Robot Mode": [
#         "Beep boop. Emotions not found. Restarting... 🤖",
#         "00101010010 = 'You're awesome' in binary!"
#     ]
# }
# 
# if mood:
#     st.write("💬 Here's something for your mood:")
#     st.info(random.choice(jokes[mood]))
# 
# if st.button("🎲 Give me a surprise mood"):
#     random_mood = random.choice(list(jokes.keys()))
#     st.write(f"🎉 Surprise! You're now feeling {random_mood}")
#     st.success(random.choice(jokes[random_mood]))
#

from pyngrok import ngrok, conf
import threading

# Set ngrok authtoken
conf.get_default().auth_token = "2zAMb3yKpW8NdulWVpi6qJXDqGe_3tSGP4dhdDhhmWLHhqWU3"

# Function to launch Streamlit app
def run_streamlit():
    !streamlit run app.py --server.enableCORS false --server.enableXsrfProtection false

# Start Streamlit app in a background thread
thread = threading.Thread(target=run_streamlit)
thread.start()

# Connect using ngrok with explicit protocol
public_url = ngrok.connect(addr="8501", proto="http")
print("🌐 Your humorous app is live at:", public_url)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import random
# from pyngrok import ngrok, conf
# import threading
# import time
# 
# # Set your ngrok authtoken here
# conf.get_default().auth_token = "2zAMb3yKpW8NdulWVpi6qJXDqGe_3tSGP4dhdDhhmWLHhqWU3"  # ← Replace this
# 
# # Streamlit UI setup
# st.set_page_config(page_title="😂 Mood Swing Machine", page_icon="🎭")
# 
# # Page styling
# st.markdown("""
#     <style>
#         body {
#             background: linear-gradient(to right, #fbc2eb, #a6c1ee);
#         }
#         .stApp {
#             font-family: 'Comic Sans MS', cursive;
#         }
#     </style>
# """, unsafe_allow_html=True)
# 
# st.title("🎭 Mood Swing Machine")
# st.markdown("Welcome to the most unpredictable app you'll ever use!")
# 
# moods = ["😄 Happy", "😢 Sad", "😡 Angry", "😴 Sleepy", "🤪 Crazy", "🤖 Robot Mode"]
# mood = st.selectbox("What's your current vibe?", moods)
# 
# jokes = {
#     "😄 Happy": [
#         "You're so bright, even the sun wears shades around you 😎",
#         "Happiness is contagious—stay away, I’m not insured!"
#     ],
#     "😢 Sad": [
#         "Don't cry... even onions feel bad when you cry 😢",
#         "If life gives you lemons, squirt them back in its eye!"
#     ],
#     "😡 Angry": [
#         "Take a deep breath... now scream into a pillow. Feel better? No? Good. 😂",
#         "Smash something! (Preferably the like button 👍)"
#     ],
#     "😴 Sleepy": [
#         "Coffee won’t help. But dreaming about coffee might ☕💤",
#         "Nap hard, nap proud 💤💪"
#     ],
#     "🤪 Crazy": [
#         "You clicked this on purpose, didn't you? Seek help. 😂",
#         "Bananas called. They want their crazy back 🍌"
#     ],
#     "🤖 Robot Mode": [
#         "Beep boop. Emotions not found. Restarting... 🤖",
#         "00101010010 = 'You're awesome' in binary!"
#     ]
# }
# 
# gifs = {
#     "😄 Happy": "https://media.giphy.com/media/3orieUXfR0ytJz8zIY/giphy.gif",
#     "😢 Sad": "https://media.giphy.com/media/d2lcHJTG5Tscg/giphy.gif",
#     "😡 Angry": "https://media.giphy.com/media/11tTNkNy1SdXGg/giphy.gif",
#     "😴 Sleepy": "https://media.giphy.com/media/3og0IPxMM0erATueVW/giphy.gif",
#     "🤪 Crazy": "https://media.giphy.com/media/3ohs7KViF7YBqsrxt6/giphy.gif",
#     "🤖 Robot Mode": "https://media.giphy.com/media/3oEjHOEqD9G4F3kXZu/giphy.gif"
# }
# 
# # History using session state
# if 'history' not in st.session_state:
#     st.session_state.history = []
# 
# if mood:
#     st.subheader("💬 Here's something for your mood:")
#     st.image(gifs[mood], width=300)
#     st.info(random.choice(jokes[mood]))
#     st.session_state.history.append(mood)
# 
# if st.button("🎲 Give me a surprise mood"):
#     surprise_mood = random.choice(moods)
#     st.toast("Mood upgraded! 🎉", icon="🎭")
#     st.success(f"🎉 Surprise! You're now feeling {surprise_mood}")
#     st.image(gifs[surprise_mood], width=300)
#     st.success(random.choice(jokes[surprise_mood]))
#     st.session_state.history.append(surprise_mood)
# 
# st.sidebar.title("📜 Mood Memory")
# if st.session_state.history:
#     st.sidebar.write("You've felt:")
#     st.sidebar.write(", ".join(st.session_state.history))
# else:
#     st.sidebar.write("No moods recorded yet.")

import os
import subprocess

def start_streamlit():
    os.system("streamlit run app.py --server.enableCORS false --server.enableXsrfProtection false")

def start_ngrok():
    time.sleep(2)  # wait for server to be ready
    url = ngrok.connect(8501)
    print("🌐 App is live at:", url)

if __name__ == "__main__":
    threading.Thread(target=start_streamlit).start()
    threading.Thread(target=start_ngrok).start()